WIP antti/postgres
samuliasmala/lahjalista pull request #11
Opened 2024-02-21 09:38 UTC by anttiasmala

Pohja tehty Postgresille

2024-02-21 12:30 UTC, anttiasmala commented on utils/prismaClient.ts
> +  var prisma: undefined | ReturnType<typeof prismaClientSingleton>; //eslint-disable-line no-var
Tämä eslint-errorin ohitus on jätetty tarkoituksella, jotta tuo global-prisma toimisi. En toki tiedä onko parhain tapa toteuttaa PrismaClientin käyttö.

2024-02-21 12:34 UTC, anttiasmala commented on prisma/migrations/20240219114215_random_number/migration.sql
> +ALTER TABLE "Gift" ADD COLUMN     "randomNumber" INTEGER;
Tämä tiedosto taitanee olla aivan turha, koska poistan tuon kolumnin heti perään 😄 Kannattaako tämmöiset testit poistaa suoraan?

2024-02-21 12:37 UTC, anttiasmala commented on pages/index.tsx
> +  receiver: string;
Vaihdoin name -> receiver. On selkeämpi omasta mielestä, kun käyttää `gift.receiver` verrattuna `gift.name`

2024-02-21 12:39 UTC, anttiasmala commented on pages/api/gifts/[uuid].ts
> +}
En poistanut tätä PUT-handleria vielä. Kannattaako tämmöiset säästää myöhempää mahdollista käyttöä varten, vai poistanko suoraan? Omasta mielestä tuo PATCH on paljon näppärämpi kuin PUT

2024-02-25 13:48 UTC, samuliasmala requested changes
Hyvää työtä! 👍   Tietokannan käyttäminen ei ole yksinkertaista, kuten olet varmasti huomannut.

Lisää vielä `.env.example` tiedoston, mistä näkee mitä env-muuttujia pitää/voi olla. Sisältö voisi olla esim. tämmöinen:

```
PORT=3000
DATABASE_URL=postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public
```

Tämän tiedoston voi sitten kopioida `.env` tiedostoksi ja laittaa muuttujiin haluamansa arvot.

2024-02-25 13:48 UTC, samuliasmala commented on prisma/migrations/20240219114215_random_number/migration.sql
> +ALTER TABLE "Gift" ADD COLUMN     "randomNumber" INTEGER;
Yleensä migraatiotiedostoja on yksi PR:ää kohden. Eli kun koodaa uuttaa taskia käyttää `prisma db push` komentoa testailuun ja sitten kun on valmis tekemään muutokset generoi yhden migraation `prisma migrate dev` komennolla. Jos PR:n aikana skeemaan tulee lisää muutoksia, niin sitten voi luoda toisen migraatiotiedoston tai muokata vanhaa. Lokaalissa testissä ja PR-katselmoinnissa tietokanta ei sisällä mitään kriittistä, joten aina voi luoda uuden tietokannan ja ajaa migraatiot alusta.

Kannattaa lukea https://www.prisma.io/docs/orm/prisma-migrate/workflows/prototyping-your-schema

2024-02-25 13:48 UTC, samuliasmala commented on pages/index.tsx
> +export type CreateGift = Omit<Gift, 'uuid'>;
Prisman käyttämät tyypit saa muuten importattua seuraavasti. Tämä voisi olla hyvä sisältö `shared/types.ts` tiedostolle:

```ts
import { Prisma, Gift as PrismaGift } from '@prisma/client';

export type Gift = Omit<PrismaGift, 'id'>;
export type CreateGift = Omit<Prisma.GiftCreateInput, 'uuid'>;
```

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/index.ts
> +  return res.status(200).json(gifts as Gift[]);
Nyt ` as Gift[]` voi poistaa (tästä ja muista vastaavista paikoista), kun paluuarvolla on jo tyyppi.

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/index.ts
> +  const gifts = await prisma.gift.findMany({
Lisäämällä tyypin `NextApiResponse`en välttää virheitä, kun TypeScript huomauttaa jos paluutyyppi on väärä. Tämä ei aiemmin toiminut, kun Axios ei palauttanut tyyppejä, mutta nyt Prisman kanssa toimii hienosti. Laittaisin sen jokaiseen API-funktioon joka palauttaa dataa.
```suggestion
async function handleGET(req: NextApiRequest, res: NextApiResponse<Gift[]>) {
```

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/index.ts
> +  const reqHandler = req.method !== undefined && HANDLER[req.method];
Siirtäisin tämän varmuuden vuoksi takaisin `try`-blokin sisälle.

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/[uuid].ts
> +  })) as Gift;
Prisman pitäisi palauttaa oikea tyyppi, eli poistetaan `as Gift` tästä ja muualta vastaavista.

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/[uuid].ts
> +      gift: newGiftData['gift'],
Toimii näinkin, mutta käyttäisin systemaattista merkintätapaa, eli tässäkin `newGiftData.received` enkä hakasulkeita (niitä käytän itse vain jos kenttä sisältää erikoismerkkejä jotka vaativat hakasulkeet).

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/[uuid].ts
> +}
Säilyttäisin tämän kun on tehty. Sitä saattaa vielä tarvita.

2024-02-25 13:48 UTC, samuliasmala commented on pages/api/gifts/[uuid].ts
> +}
Makuasia kumpaa haluaa käyttää. Tässä sun valitsemassa tavassa ei tarvitse tässä kohtaa tarkistaa löytyikö lahjaa, mutta sitten pitää käsitellä virhe erikseen kuten teetkin. Eli ihan hyvä näin.

2024-02-25 13:48 UTC, samuliasmala commented on package.json
> +    "node": ">=20",
Itse asettaisin version täsmälleen 20 eli `^20`, ei välttämättä toimi versioilla 21, 22, 23 jne.

2024-02-25 13:48 UTC, samuliasmala commented on package.json
> +    "pg": "8.11.3",
Mihin tarvitaan `pg` pakettia ja sen tyyppejä?

2024-02-25 13:48 UTC, samuliasmala commented on package.json
> +    "prisma": "5.9.1"
`prisma` pitäisi olla tavallinen dependency, ei dev dependency.

2024-02-26 11:54 UTC, anttiasmala commented on utils/prismaClient.ts
> +  var prisma: undefined | ReturnType<typeof prismaClientSingleton>; //eslint-disable-line no-var
Oli jäänyt joo tuo = prisma lopusta. Se kyllä näytti toimivan silti :smile:

2024-02-26 11:55 UTC, anttiasmala commented on prisma/migrations/20240219115012_remove_random_number/migration.sql
> +ALTER TABLE "Gift" DROP COLUMN "randomNumber";
Tähän vastattu yllä: https://github.com/samuliasmala/lahjalista/pull/11#discussion_r1501817615

2024-02-26 22:00 UTC, anttiasmala commented on .env.example
> +DATABASE_URL="postgresql://johndoe:databasepassword@localhost:5432/mydb?schema=public"
En tiedä hiffasinko tämän väärin. Olisiko tähän pitänyt laittaa `mydb`:n tilalle se oikea databasen nimi mitä käytän?

2024-02-26 22:04 UTC, anttiasmala commented on pages/api/gifts/[uuid].ts
> +  res: NextApiResponse<Gift>;
En oikein osaa käyttää kovin hyvin vielä tätä GitHubin rivikommentointia. Mutta olisiko tähän parempaa tapaa toteuttaa tyypin antaminen tai tarvitaanko tässä edes ylipäätään tyyppiä `NextApiResponse`:lle?

2024-02-26 22:10 UTC, anttiasmala commented
Kiitos jälleen tarkistuksesta! :) Nyt pitäisi olla kaikki korjailtu.

Tähän neuvoon  https://github.com/samuliasmala/lahjalista/pull/11#discussion_r1501820187  viittaavia korjaamattomia tai väärin korjattuja kohtia saattanee löytyä, pitää tuota harjoitella ja testailla, jotta pystyn olemaan varma osaamisestani :smile:

2024-02-26 22:17 UTC, anttiasmala commented on pages/api/gifts/[uuid].ts
> +};
Olisiko tälle parempaa tapaa toteuttaa tyypin antaminen `NextApiResponse`:lle? Tuo tapa toiminee niin kauan, kun joku handlereista ei palauta listaa (arrayta). Silloin tuo pitäisi olla `res: NextApiResponse<Gift[]>;`

Vertaan tuota tapaa tähän tapaan:
 `async function handleGET(req: NextApiRequest, res: NextApiResponse<Gift[]>) {` 
jonka näytit tässä kommentissa https://github.com/samuliasmala/lahjalista/pull/11/commits/a8f2d69e05a9ee213591dc12a6139d8e6ba5d8f7#r1501820187

2024-02-28 19:55 UTC, samuliasmala commented on .env.example
> +DATABASE_URL="postgresql://johndoe:databasepassword@localhost:5432/mydb?schema=public"
Ihan oikein tajusin. Jokainen voi käyttää haluamaansa db:n nimeä, joten tuo on noin hyvä.

`.env` tiedosto pitää muuten lisätä vielä `.gitignore` tiedostoon.

2024-02-28 19:55 UTC, samuliasmala commented on package.json
> +    "node": ">=20",
Tämä muutos vielä tekemättä.

2024-02-28 19:55 UTC, samuliasmala commented on package.json
> +    "pg": "8.11.3",
Joo nyt pitäisi olla turha.

2024-02-28 20:04 UTC, samuliasmala requested changes
Kommenttien lisäksi tekisin vielä kaksi muutosta:
* README.md tiedostoon ohjeet miten otetaan käyttöön, eli
  1. Luo `.env` tiedosto `.env.example` tiedostosta
  2. Aja migraatiot `npx prisma migrate deploy`
 * Poistaisin kaikki migraatiot ja tyhjentäisin tietokannan, ja sitten generoisin skeemasta yhden uuden migraation niin poistuisi nuo testit.

2024-02-29 21:44 UTC, anttiasmala commented on README.md
> +
En ole README.md tiedostoja koskaan tehnyt, joten en tiedä onko tuo ollenkaan hyvä. :smile: Onko esimerkiksi rivit 23 - 25 turhat?

2024-03-01 19:27 UTC, samuliasmala commented on README.md
> +
Hyvin kirjoitettu tuo. Ja ei ole rivit 23-25 turhia. Erityisesti on hyvä tieto, että tietokantaa ei tarvitse itse luoda, vaan Prisma tekee sen.

2024-03-01 19:33 UTC, samuliasmala approved these changes
Hienoa työtä!! 💪 Valmis mergettäväksi.

2024-03-01 20:50 UTC, merged