Antti | Error structure changes
samuliasmala/lahjalista pull request #17
Opened 2024-03-05 12:42 UTC by anttiasmala

Tein muutaman pienen muutoksen koskien virhekoodeja / virheiden käsittelyä. En ollut tyytyväinen tuohon vanhaan tapaan, joten ajattelin hiukan päivittää sitä. Ei mitään isoja muutoksia, mutta jotain pientä

2024-03-05 12:44 UTC, anttiasmala commented on package-lock.json
Tämä tiedosto on mun tietokoneella olevasta `main`-branchista. Tätä ei ole pushattu mihinkään, joten siksi näkyy näin. Kopioin tämän branchin `main`-branchista

2024-03-05 12:46 UTC, anttiasmala commented on pages/api/gifts/index.ts
> -}
En sisällyttänyt `e instanceof Error`:ia tuolla `handleError.ts`-tiedostossa, koska en saanut toistettua mitään muita virheitä kuin Prisman

2024-03-05 12:49 UTC, anttiasmala commented
Olisiko järkevämpää käydä muita Prisman virhekoodeja läpi jo tässä vaiheessa vaiko vasta myöhemmin tarvittaessa? Nyt muut Prisman virhekoodit vain palauttavat `Server error!`

2024-03-07 19:59 UTC, samuliasmala commented
> Olisiko järkevämpää käydä muita Prisman virhekoodeja läpi jo tässä vaiheessa vaiko vasta myöhemmin tarvittaessa? Nyt muut Prisman virhekoodit vain palauttavat `Server error!`

Ei kannata käydä muita Prisman virhekoodeja läpi, mutta kannattaa lisätä `console.error(error); juuri ennen "Server error"in palauttamista, niin saat serverin konsoliin tiedon virheestä.

2024-03-07 20:00 UTC, samuliasmala requested changes
Hyvältä näyttää, pari kommenttia.

2024-03-11 09:25 UTC, anttiasmala commented on components/DeleteModal.tsx
> +      handleGiftError(e);
Onko tämä ollenkaan järkevä?

2024-03-11 09:27 UTC, anttiasmala commented on frontend/handleError.ts
> +}
Menin mentaliteetillä tehdään ensin ja kysytään sitten :sweat_smile: 

Onko tämä ihan ok vai onko muutettavaa / perutaanko? :smile:

2024-03-11 20:51 UTC, samuliasmala requested changes

2024-03-11 20:51 UTC, samuliasmala commented on frontend/handleError.ts
> +}
Hyvä muutos. Siirtäisin tiedoston vielä `utils` kansioon. Kaikki muut kansiot ovat frontendiä paitsi `backend` ja `prisma`, joten frontendille ei kannata tehdä omaa kansiotaan.

2024-03-11 20:51 UTC, samuliasmala commented on components/DeleteModal.tsx
> +      handleGiftError(e);
Kyllä on!

2024-03-11 20:51 UTC, samuliasmala commented on backend/handleError.ts
> +      return res.status(404).send('Record was not found on the server!');
Tekisin tästä geneerisen, joka toimii kaikilla modeleilla:
```suggestion
      const modelName =
        typeof e.meta?.modelName === 'string' ? e.meta?.modelName : 'Record';
      return res.status(404).send(modelName + ' was not found on the server!');
```

2024-03-13 17:21 UTC, anttiasmala commented on backend/handleError.ts
> +      return res.status(404).send('Record was not found on the server!');
Vau! Tämä oli hyvä, kiitos!! Ei käynyt edes mielessä, vaikka hyvin simppeli tapa onkin :smile:

2024-03-14 12:29 UTC, merged