Antti | api/user
samuliasmala/lahjalista pull request #18
Opened 2024-03-05 15:40 UTC by anttiasmala

Nyt on toimiva API myös käyttäjille. Tätä ei ole vielä linkitetty mihinkään login-sivuun vaan tein testit REST Clientillä. Käytin tässä vielä Insomniaa, tajusin liian myöhään tämän VS Coden REST Clientin. Pahoittelut tästä. Toisaalta testejä tuli tehtyä varmaan sata, että toisaalta tuo olisi täyttynyt melkoisesti :smile:

2024-03-05 15:41 UTC, anttiasmala commented on pages/api/users/[uuid].ts
> +}
Tämä PUT-handler ei muuten toimi PUT-menetelmällä vaan toimii PATCH-menetelmällä. Tässä on pieni bugi, elikkä pystyy vaihtamaan mitä tahansa lähettämällä requestin. Vaikka oman ID:n, UUID:n tai esim. `createdAt`:n arvon :smile:

2024-03-05 16:04 UTC, anttiasmala commented on prisma/schema.prisma
Nämä tulevat `antti/user-model`-branchista, käytin sitä pohjana vaikka siitäkin on PR https://github.com/samuliasmala/lahjalista/pull/16

2024-03-05 16:04 UTC, anttiasmala commented on shared/types.ts
Nämä tulevat antti/user-model-branchista, käytin sitä pohjana vaikka siitäkin on PR https://github.com/samuliasmala/lahjalista/pull/16

2024-03-05 21:50 UTC, anttiasmala commented
> Tästähän uupuu kokonaan tuo salasanan kryptaus, unohdin sen

Nyt sekin on tehty! :+1:

2024-03-07 19:48 UTC, samuliasmala requested changes
Muutama kommentti, mutta hienosti toimi jo nyt! Ja kiitos `api.rest` tiedostoon lisätyistä user-requesteista, oli helppo testata rajapinnan toimivuus niiden avulla 👍

2024-03-07 19:48 UTC, samuliasmala commented on api.rest
> +GET {{baseUrl}}/gifts/1141b4b1-7ea3-40dd-853c-1a0f9eecb4b5
Tässä pitäisi ola users
```suggestion
GET {{baseUrl}}/users/1141b4b1-7ea3-40dd-853c-1a0f9eecb4b5
```

2024-03-07 19:48 UTC, samuliasmala commented on pages/api/users/index.ts
> +import * as bcrypt from 'bcrypt';
Näitä `import * as` kannattaa välttää jos mahdollista. Tässä parempi importata vain hash mikä tarvitaan.
```suggestion
import { hash } from 'bcrypt';
```

2024-03-07 19:48 UTC, samuliasmala commented on pages/api/users/index.ts
> +  }
Koska schema.prisma tiedostossa sähköpostille on asetettu `@unique` voi olla että tämä tarkistus ei ole pakollinen tässä, vaan voitaisiin jättää se tietokannalle. Mutta en tiedä olisiko tuloksena tuleva virheilmoitus niin hyvä ja selkeä kuin nyt.

EDIT: ja `@unique` ei osaa huomioida, että sähköposteissa isot ja pienet kirjaimet ovat samoja.

2024-03-07 19:48 UTC, samuliasmala commented on pages/api/users/index.ts
> +  });
Tässä tarkistuksessa on se ongelma, että `john.doe@doemail.com` ja `John.doe@doemail.com` tulkitaan kahdeksi eri sähköpostiksi vaikka ne ovat yksi ja sama -> tässä pitäisi tehdä case-insensitive haku kun tarkistetaan onko sähköposti uniikki -> ehkä helpointa, että sähköpostit muutetaan aina lowercase ennen tietokantaan tallennusta.

2024-03-07 19:48 UTC, samuliasmala commented on pages/api/users/[uuid].ts
> +      email: newUserDetails.email,
Tässä ei tarkisteta onko uudella sähköpostiosoitteella olemassa jo käyttäjä. Jos sähköpostiosoitteet muutetaan aina pieniksi kirjaimiksi, niin silloin tietokanta tekee tarkistuksen -> tähän tarvitsee vain `toLowerCase()`.

Tässä ei myöskään tarkisteta sähköpostin oikeellisuutta, mutta sitä ei tarvitse lisätä sillä tarkistus tulee issuessa #19.

2024-03-07 19:48 UTC, samuliasmala commented on pages/api/users/[uuid].ts
> +    data: newUserDetails,
Sama juttu, että sähköpostia ei tarkisteta/muuteta pieniksi kirjaimiksi.

2024-03-07 19:48 UTC, samuliasmala commented on pages/api/users/[uuid].ts
> +}
Hoidetaan molemmat ongelmat myöhemmin issuessa #19 missä validoidaan käyttäjän syötteet.

2024-03-07 19:48 UTC, samuliasmala commented on prisma/schema.prisma
Aivan oikea tapa toimia näin!

2024-03-11 11:30 UTC, anttiasmala commented on pages/api/users/index.ts
> +  }
Tämä on kauhea tapa selvittää nämä errorit. Vaihdetaan parempaan kun #17 on valmis!

2024-03-11 11:36 UTC, anttiasmala commented on api.rest
Ajattelin, että kommentit olisivat helpottaneet tätä, mutta siitä taisikin tulla todella paljon sekavampi :sweat_smile: :rofl: 

Olisiko tässä kohtaa järkevä tehdä omat `.rest-tiedostot`. Esim `gifts.rest` ja `users.rest`?

2024-03-11 20:33 UTC, samuliasmala requested changes

2024-03-11 20:33 UTC, samuliasmala commented on pages/api/users/[uuid].ts
> +    },
Annetaan olla tässä kohtaa ja korjataan myöhemmin.

2024-03-11 20:33 UTC, samuliasmala commented on pages/api/users/[uuid].ts
> +      email: newUserDetails.email.toLowerCase(),
Tässä näkee hyvin miksi `as` on vaarallinen. Koska kyseessä on PATCH endpoint kaikki kentät eivät ole pakollisia -> `newUserDetails.email` voi olla `undefined` jolloin pitää käyttää conditional chaining operaattoria. TypeScript ei osaa varoittaa, koska `const newUserDetails = req.body as User;` antaa sille virheellisen tyypin. Itse asiassa tuo tyyppi kannattaa muuttaa oikeaksi:
```ts
const newUserDetails = req.body as Partial<User>;
```


```suggestion
      email: newUserDetails.email?.toLowerCase(),
```

2024-03-11 20:33 UTC, samuliasmala commented on api.rest
Noista sun lisäämistä kommenteista ei hirveästi ole hyötyä, kun osoite ja http-verbi oikeastaan kertoo saman.

Pitäisin itse vielä samassa tiedostossa ja erottaisin kommenteilla, esim. näin:

```
# GIFT REQUESTS


# USER REQUESTS
```

2024-03-11 20:33 UTC, samuliasmala commented on api.rest
> +# For example: GET {{baseUrl}}/gifts/2ebac01e-4586-4f2a-9fbd-486770ce04af
Mielestäni on paljon selkeämpi, että kyseisissä requesteissa on id valmiiksi laitettu, vaikka se ei vastaakaan mitään sinun tietokannan id:tä. Se on helppo korvata halutulla. Eli esim.
```
GET {{baseUrl}}/gifts/1141b4b1-7ea3-40dd-853c-1a0f9eecb4b5
```
parempi kuin että päättyy / merkkiin.

2024-03-13 18:10 UTC, samuliasmala approved these changes
Hyvää työtä! 👍 Voi mergetä.

2024-03-14 12:25 UTC, merged