Antti/modal
samuliasmala/lahjalista pull request #2
Opened 2023-10-25 07:53 UTC by anttiasmala

Ensimmäinen prototyyppi modalista tehty.

2023-10-25 08:00 UTC, anttiasmala commented
Näköjään tuo TODO.md tuli mukana, vaikka laitoin sen .gitignore-tiedostoon. Eipä siinä mitään salaista ole :smile: 

Committin tekstejä ei taida pystyä enää jälkikäteen muuttamaan? Huomasin, että olin huonosti laittanut tuon yhden commitin "Changed AcceptDeclineModal to DeleteModal". Kysessä oli .tsx-tiedoston nimen vaihtaminen, tuosta ainakin itse saan käsityksen, että ainoastaan komponentin nimi vaihtui

2023-10-27 08:08 UTC, anttiasmala commented
Yleisellä tasolla kysymys.

Olisiko järkevämpää heti alusta asti tehdä esimerkiksi tästä DeleteModal:sta "globaali", elikkä että sitä voisi käyttä muissa tilanteissa tässä projektissa myös?

Tämä `components/DeleteModal.tsx` on toimiva vain tässä lahjaidean poistamisessa eikä se toimi missään muussa tilanteessa. Onko tämä ihan okei, vai pitäisikö tuosta tehdä "globaali" vaihtamalla esim `gift`-proppi --> `data` jne?

Jos tuo on ihan okei, että DeleteModal.tsx toimii vain lahjaidean poistamisessa, pitäisikö sille tehdä oma folderi tuonne `components`-kansion sisään? Esim: `components/lahjaidea/DeleteModal.tsx` tai muu vastaava, jotta tietää missä DeleteModal.tsx on käytössä / missä se toimii pelkästään?

Esimerkiksi tuo `components/Modal.tsx` on "globaali" jo nyt, sillä data tulee `children`-propsina ja kahdelle containerille voi antaa tyylit tarvittaessa `className`-propsina.

Omissa projekteissa tuo kansiointi räjähtää käsiin aina melko pahasti :smile:

2023-11-19 11:19 UTC, samuliasmala commented
> Näköjään tuo TODO.md tuli mukana, vaikka laitoin sen .gitignore-tiedostoon. Eipä siinä mitään salaista ole 😄

Ainakaan mulle tuo tiedosto ei näy, joten .gitignore näyttäisi toimivan.

> Committin tekstejä ei taida pystyä enää jälkikäteen muuttamaan? Huomasin, että olin huonosti laittanut tuon yhden commitin "Changed AcceptDeclineModal to DeleteModal". Kysessä oli .tsx-tiedoston nimen vaihtaminen, tuosta ainakin itse saan käsityksen, että ainoastaan komponentin nimi vaihtui

`git rebase` ja `git amend` komennoilla commitin tekstiä voi muuttaa, mutta em. komennon käyttö korvaa muutettavan commitin ja kaikki sen jälkeen tulevat commitit uusilla, joten jos commitit on jo pushattu repoon pitää ne force pushata sinne. Ja jos joku on jo ehtinyt pullaamaan ne, niin tulee konflikteja --> em. komentoja on syytä käyttää vain committeihin, joita ei ole vielä pushannut.

2023-11-19 11:58 UTC, samuliasmala commented
> Olisiko järkevämpää heti alusta asti tehdä esimerkiksi tästä DeleteModal:sta "globaali", elikkä että sitä voisi käyttä muissa tilanteissa tässä projektissa myös?

Toistaiseksi ei. Sitten jos myöhemmin tulee tarve toiselle vastaavalle, niin voi miettiä siirtääkö joitakin osia DeleteModal:ista yhteiseen ConfirmModal tms. komponenttiin. Mutta yleensä ei kannata kovin paljon tehdä etukäteen vaan vasta kun tarve tulee.

> Tämä `components/DeleteModal.tsx` on toimiva vain tässä lahjaidean poistamisessa eikä se toimi missään muussa tilanteessa. 

Onko tämä ihan okei, vai pitäisikö tuosta tehdä "globaali" vaihtamalla esim `gift`-proppi --> `data` jne?
Nykyinen on ok.

> Jos tuo on ihan okei, että DeleteModal.tsx toimii vain lahjaidean poistamisessa, pitäisikö sille tehdä oma folderi tuonne `components`-kansion sisään? Esim: `components/lahjaidea/DeleteModal.tsx` tai muu vastaava, jotta tietää missä DeleteModal.tsx on käytössä / missä se toimii pelkästään?

Ei kannata, nykyinen hakemistorakenne on hyvä.

> Esimerkiksi tuo `components/Modal.tsx` on "globaali" jo nyt, sillä data tulee `children`-propsina ja kahdelle containerille voi antaa tyylit tarvittaessa `className`-propsina.

Hmm, onkohan sulla jäänyt pushaamatta jotain? Ainakaan repossa olevassa versiossa tyylejä ei voi antaa `className` propin avulla.

2023-11-19 11:59 UTC, samuliasmala requested changes
Alla joitakin kommentteja. Tuo antti/modal_github-action-error-fix minkä meinasit toisessa PR:ssä mergetä lokaalisti taitaa olla vielä pushaama repoon?

2023-11-19 11:59 UTC, samuliasmala commented on components/Modal.tsx
> +}
Ehdotan Modal-komponentiksi seuraavaa, jossa seuraavia muutoksia:
* div-elementin propsit tyyppi poistettu, kun niitä ei käytetty mihinkään (jäljelle pelkkä children-propsi)
* Container korvattu divillä (Container on identtinen sen kanssa, joten tarpeeton
* Modaalin kuuluu mennä kaiken muun päälle, joten lisätty harmaa huntu muun sisällön päälle ja renderöity `createPortal`in avulla, jotta menee sen hetkisen sisällön ulkopuolelle
* z-indeksien arvoilla 98 ja 99 varmistettu, että menee kaiken muun sisällön päälle.

```suggestion
import { ReactNode } from 'react';
import { createPortal } from 'react-dom';

export function Modal({ children }: { children: ReactNode }) {
  return createPortal(
    <>
      <div className="fixed left-0 top-0 z-[98] h-full w-full bg-black opacity-20" />
      <div className="absolute z-[99] top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%] ">
        <div className="grid w-96 sm:w-96 border border-yellow-300 bg-white">
          {children}
        </div>
      </div>
    </>,
    document.body,
  );
}
```

2023-11-19 11:59 UTC, samuliasmala commented on components/DeleteModal.tsx
> +type ModalType = ButtonHTMLAttributes<HTMLButtonElement> & {
`ButtonHTMLAttributes<HTMLButtonElement>` on tyypissä mukana turhaan, kun niitä ei käytetä mihinkään -> poistetaan.

2023-11-19 11:59 UTC, samuliasmala commented on components/DeleteModal.tsx
> +  giftListRefreshFunction?: () => void;
Ovatko nämä tarkoituksella optional-parametreja? Eikös niitä kumpaakin tarvita?

2023-11-19 11:59 UTC, samuliasmala commented on components/DeleteModal.tsx
> +  if (typeof closeModalUseState === 'undefined') return;
Funktion argumenttien tyypit eivät salli `closeModalUseState` arvoa `undefined`, joten tämän rivin voi varmaan poistaa tarpeettomana?

2023-11-19 11:59 UTC, samuliasmala commented on components/DeleteModal.tsx
> +        alt="acceptButton"
alt-tekstin on tarkoitus korvata kuva jos kuvaa ei jostain syystä voi näyttää (nettiongelma, näkövammaiset), joten Parempi teksti tähän olisi ihmisen luettavaksi tehty esim. "Accept deletion".

2023-11-19 11:59 UTC, samuliasmala commented on components/DeleteModal.tsx
> +        alt="declineButton"
Tämä teksti voisi olla esim "Cancel"

2023-11-19 11:59 UTC, samuliasmala commented on pages/index.tsx
> +  const [openModal, setOpenModal] = useState(false);
Itse suosin tämän tyyppisissä boolean-muuttujissa is-alkua, eli `isModalOpen` ja `setIsModalOpen`. Toki vähän makuasia.

2023-11-19 11:59 UTC, samuliasmala commented on pages/index.tsx
> +                closeModalUseState={setOpenModal}
Itse muuttaisin `closeModalUseState` parametrin nimen `setIsModalOpen`.

2023-11-19 11:59 UTC, samuliasmala commented on components/DeleteModal.tsx
> +  if (typeof gift === 'undefined') dataToDeleteInfo = 'No data was given';
Voisiko `gift` asettaa pakolliseksi parametriksi, jolloinrivi 25 olisi tarpeeton ja `${gift?.name} - ${gift?.gift}` voisi viedä suoraan return-lausekkeeseen?

2023-11-29 08:14 UTC, anttiasmala commented
> Hmm, onkohan sulla jäänyt pushaamatta jotain? Ainakaan repossa olevassa versiossa tyylejä ei voi antaa `className` propin avulla.

Oli jäänyt pushaamatta ja tuo versio, jossa propeilla pystyy antamaan className:lle arvoja onkin tehty tuonne antti/json-server -branchiin. Katson tuon vaikka Merge-vaiheessa, että onko tarpeellinen, luulen että ei.

2023-12-18 07:29 UTC, samuliasmala requested changes

2023-12-18 07:29 UTC, samuliasmala commented on svg-icons/accept_button-icon.svg
Tarvitaanko tätä tiedostoa, kun löytyy myös `public/images/icons` kansiosta?

2023-12-18 07:29 UTC, samuliasmala commented on svg-icons/decline_button-icon.svg
Tarvitaanko tätä tiedostoa, kun löytyy myös `public/images/icons` kansiosta?

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
> +      <button
Tässä on hyvä käyttää `Button` komponenttia, kun semmoinen löytyy.

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
> +      <button
Tässä on hyvä käyttää `Button` komponenttia, kun semmoinen löytyy.

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
> +        }}
Mouse over tyylittelyt on parempi tehdä `hover:bg-gray-600` classNamella suoraan buttoniin (hover on CSS ominaisuus, ei sinänsä liity Tailwindiin). Ks. [Tailwindin dokumentaatio](https://tailwindcss.com/docs/hover-focus-and-other-states#hover-focus-and-active) lisäinfoksia.

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
> +          }
Sama kuin yllä, käytä `hover`ia. Kysy jos tarvitset apua miten tehdään.

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
> +        }}
Sama kuin yllä, käytä hoveria.

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
> +          }
Sama kuin yllä, käytä hoveria.

2023-12-18 07:29 UTC, samuliasmala commented on components/DeleteModal.tsx
>          {dataToDeleteInfo}
Selkeämpi ilman muuttujaa.
```suggestion
        {gift.name} - {gift.gift}
```

2023-12-18 07:29 UTC, samuliasmala commented on pages/index.tsx
> +}
Tarpeeton välikomponentti. Parempi lisätä `isModalOpen` suoraan `Modal` komponenttiin, ja heti komponentin alussa testata onko modaali auki: `if (!isModalOpen) return null;` Ja sitten valin välität `isModalOpen`tiedon `DeleteModal`lin kautta `Modal` komponentille.

2023-12-18 07:29 UTC, samuliasmala commented on icons/accept_button_icon.tsx
> +};
Nyt `svgr`:n generoimaa koodia on muokattu lisäämällä custom-propit. Sikäli huono, että aina kun ajaa `npm run svgr` nuo häviävät ja pitää olla varovainen ettei niitä commitoi. @aleksiasmala olisiko sulla joku idea miten tämä kannattaisi tehdä?

2023-12-19 09:53 UTC, samuliasmala commented on icons/accept_button_icon.tsx
> +};
Tätä pitää vielä miettiä voisiko jotenkin parantaa, mutta tehdään se myöhemmin.

2023-12-19 09:54 UTC, samuliasmala approved these changes
Nyt näyttää erinomaiselta! Nämä viimeisimmät muutokset selkeyttivät koodia merkittävästi! 👍

2023-12-20 12:50 UTC, merged