Antti/register error structure changes
samuliasmala/lahjalista pull request #22
Opened 2024-03-22 10:06 UTC by anttiasmala

Tein pientä muutosta virheiden käsittelyyn. Yritin korvata kaikki mahdolliset HttpError-classilla. Muokkasin myös hiukan frontin virheiden käsittelyä

2024-03-22 10:07 UTC, anttiasmala commented on pages/index.tsx
> +    setIsAnyKindOfErrorMessage(errorMessage);
Jätin tämän funktion tähän, jotta useStaten arvot on helppo laittaa. Muuten joutuisi useStatejen arvojen vaihdot laittamaan `catch`-blockin alle

2024-03-22 10:09 UTC, anttiasmala commented on pages/api/users/index.ts
> +  const checkedEmailAddress = emailAddress.toLowerCase().match(emailRegex);
Tämä nyt ei varsinaisesti ollut virheiden käsittelyä, mutta muokkasin tämänkin käyttämään `emailRegex`-variablea

Se lienee ihan hyvä juttu varmistaa backendissa vielä, että arvot ovat oikeita, koska client-puoleen ei voi luottaa (API:n väärinkäyttö yms)?

2024-03-22 10:12 UTC, anttiasmala commented on utils/handleError.ts
> +    }
Onko tämmöinen funktio tarpeellinen? Jos on, olisiko tähän heittää jotain parempaa nimeä? Mietin, että onko tuo `handleDefaultError` tarpeeksi selkeä :smile: 

Tämän funktion tarkoituksena ajattelin olla semmoinen "yleinen" virheiden käsittelijä frontissa

2024-04-06 17:20 UTC, samuliasmala requested changes
Oikein hyvä! Pari pientä muutosta, ja sitten yksi konflikti pitää myös ratkaista.

2024-04-06 17:20 UTC, samuliasmala commented on backend/handleError.ts
> +      return res.status(400).send('Record was not unique!');
Tämän voisi yksinkertaistaa käyttämään samaa logiikkaa kuin P2025:
```suggestion
      const targetName =
        Array.isArray(e.meta?.target) && typeof e.meta.target[0] === 'string'
          ? e.meta.target[0]
          : 'Record';
      return res.status(400).send(`${targetName} was not unique!`);
```

2024-04-06 17:20 UTC, samuliasmala commented on pages/api/users/index.ts
> +  const checkedEmailAddress = emailAddress.toLowerCase().match(emailRegex);
On oikein hyvä ja välttämätön juttu. Issuessa #19 validointia tehdään vielä lisää.

2024-04-06 17:20 UTC, samuliasmala commented on utils/handleError.ts
> +    }
Hyvä tämmöinen funktio. Ehkä muuttaisin Default -> General.

2024-04-08 14:51 UTC, samuliasmala approved these changes
Valmis mergettäväksi! 👍

2024-04-08 15:09 UTC, merged