Toast-ilmoitukset | Antti/toast
samuliasmala/lahjalista pull request #35
Opened 2024-09-13 09:39 UTC by anttiasmala

Tässä ensimmäinen versio Toast-ilmoituksista. Toistaiseksi keskeneräinen

2024-10-10 09:27 UTC, anttiasmala commented on pages/_app.tsx
> +
Tuleeko parempaa tapaa mieleen kuin tämä?

Eli tämän tarkoitus on vain tsekata onko käyttäjä puhelimella vai ei, jolla määritetään näytetäänkö maksimissaan 1 vai 3 error-toastia.

Tämä tsekkaus on siksi täällä, koska tällä hetkellä on käytössä vain yksi `ToastContainer`

2024-10-10 09:35 UTC, anttiasmala commented on pages/login.tsx
>        }
Hetken jouduin miettimään mikä tämän idea on, mutta se on samanlainen toteutus kuin `/pages/index.tsx`:ssä. :smile: Eli jos käyttäjä yrittää kirjautua virheellisillä tiedoilla (vääränlainen sähköposti tai tyhjä salasana) ei lähetetä Login-API:iin turhaa kutsua (ei liene tarpeellista tässä kohtaa)

`errorFound`-variablen tarkoitus tässä on sama kuin `/pages/index.tsx`:ssä. Eli tarkistetaan sekä sähköposti- että salasanakenttä onko virheitä. Ilman `errorFound`ia tarkistus pysähtyisi ensimmäiseen virheeseen eli sähköpostikenttään eikä mahdollista virhettä salasanakentässä käyttäjälle näytettäisi ennenkuin sähköpostikenttä olisi virheetön

2024-10-10 09:38 UTC, anttiasmala commented on pages/login.tsx
>        };
Koodissa olevassa kommentissa on selitys

2024-10-10 09:41 UTC, anttiasmala commented on pages/login.tsx
> +}
Tämä samainen `ErrorParagraph`-componentti on nyt käytössä sekä `/pages/register.tsx` että tässä tiedostossa. Olisiko parempi tehdä oma tiedostonsa `/components`-kansioon tai vaikka tehdä `pages/register.tsx`:n `ErrorParagraph`-componentti exportableksi

Pahoittelut Finglishistä, en tiedä suomalaisia termejä esim. sanalle exportable :sweat_smile: Varmaankin jokin muuaalla käytettäväksi tmv :smile:

2024-10-10 14:29 UTC, anttiasmala commented on pages/logout.tsx
>  } as const;
Onko virheiden käsittelyyn jotain hyvää tapaa? 

Olisiko esimerkiksi se hyvä, että tekisi tuolle `handleGeneralError`-funktiolle jonkun objektin, joka sisältäisi kaikki mahdolliset virhekoodit? Eli juurikin nämä mitkä tässä nyt kommentoin + paljon muitakin. Lähinnä vain idea :smile:

2024-10-10 15:02 UTC, anttiasmala commented on utils/isPhoneUser.ts
> +}
1. Onko tarpeellista olla omassa tiedostossaan? On käytössä vain `/pages/_app.tsx`-tiedostossa
2. Parempi tapa selvittää onko käyttäjä tietokoneella tai puhelimella lienee `userAgent`ista tiedon saaminen vs tämä nykyinen tapa.

3. Jos tämä tapa on tässäkohtaa ok, niin tekisin seuraavan pienen muutoksen koodiin:

```suggestion
// CHECK THIS, onko tässä mitään järkeä?

// Ei taida olla tarpeellinen, jos tämä tarkistus tehdään ainoastaan _app.tsx-tiedostossa. Turhaan on oma tiedostonsa tälle

export function isPhoneUser(window?: Window & typeof globalThis): boolean {
  if (window) {
    if (window.screen.width < 768 || window.screen.height < 768) {
      return true;
    }
    return false;
  }
  return false;
}
```

2024-10-10 15:04 UTC, anttiasmala commented on utils/handleError.ts
> +    return 'Tuntematon virhe';
Jokainen kohta if ja else if palauttaa nyt jonkin arvon. Tätä ei jostain syystä ollut aiemmin

2024-10-11 19:19 UTC, samuliasmala requested changes

2024-10-11 19:19 UTC, samuliasmala commented on pages/login.tsx
>        };
Jep olet aivan oikeassa, TypeScript ei osaa päätellä ettei undefined ole mahdollinen errorFound muuttujan takia.

2024-10-11 19:19 UTC, samuliasmala commented on pages/login.tsx
> +}
Tekisin oman tiedoston `/components` kansioon, mitä kumpikin sivu käyttää.

Finglish toimii oikein hyvin koodauksessa, monille sanoille ei ole suomenkielistä vastinetta :)

2024-10-11 19:19 UTC, samuliasmala commented on pages/logout.tsx
>  }
Jep, selkeämpi näin.

2024-10-11 19:19 UTC, samuliasmala commented on pages/logout.tsx
>  } as const;
Hyvä idea. Voisiko `FRONT_END_HANDLER` objektia laajentaa niin, että siinä olisi kaikki virhekoodit?

2024-10-14 08:52 UTC, anttiasmala commented on pages/_app.tsx
> +        position="top-right"
Joo, `top-right` on oletusarvo. Testasin poistamalla koko `position`-arvon.

https://fkhadra.github.io/react-toastify/introduction/

Otin tuolta esimerkistä `<ToastContainer>`in. Joten voidaan hyvinkin muokata erilaiseksi :+1:

2024-10-14 12:01 UTC, samuliasmala commented on pages/_app.tsx
> +        position="top-right"
Pidetään `top-right` kun on oletusarvo.

2024-10-14 15:54 UTC, anttiasmala commented on components/ErrorParagraph.tsx
Tein oman componentin `ErrorParagraph`sta

2024-10-14 15:56 UTC, anttiasmala commented on utils/handleError.ts
>  } as const;
Vaihdoin tuon objektin nimen ja lisäsin `/pages/logout.tsx`-tiedoston virhekoodit sinne. Lisäsin vielä kommentin kertomaan mistä tiedostosta ovat peräisin

2024-10-15 05:46 UTC, samuliasmala commented on utils/handleError.ts
>  } as const;
Hyvä idea lisätä kommentti 👍

2024-10-15 05:48 UTC, samuliasmala approved these changes
Valmista mergettäväksi, hyvää työtä! 🔥 👍

2024-10-15 07:47 UTC, merged